language: node_js
dist: trusty
matrix:
  fast_finish: true
  allow_failures:
    - node_js: '6'
    - node_js: '10'
    - node_js: '11'
node_js:
  - '8'
  - '11'
  - '10'
  - '6'
env:
  global:
    - CPUS_COUNT=4
    - TRAVIS_AUTHOR_EMAIL=travis@randytarampi.ca
    - TRAVIS_AUTHOR_NAME=Travis
    - secure: AjZtkV+1NkIhUDH8PJgbKYmHRr0g1fxSXA6NyS1yeGPlbFoMaeFF/DptePrHSq4hqGxPbeBpcVsrCmksrokMvm4jWacFTeXMwy0MmKTfIoY3erK44tEWJP6q/3bYv+gPQnDX33yaNX6WDryF777/F0gbCkoEe6wZfsMXFmlTmO0qRahaIE9o75sEfd8rawJYgpr8WWFaKAiW5ZkPjv5ZgFEclSYFcOxmS8h7eimY3VIxV2iHgM7ZOiEAto/UR5YbuPM4bXBQgzBn9gnqEvhl9TRKjKSx+vEUt/3lbHFtEoLb0EyDdrKu+e4pUXd/cZuN0VCH/JQv+6UOMmTzMx4eUGYo9u60gta6wahe48E9nVSW1jmFze1scQWJnthBqLZqBYUA17LGF8EYKF14J44WlCit9g/gBHLIu6Kcqv+sEygg2ydUU8MH3bLoUquvsP3J0aLv83aDkUsl3fEDQB1A8BIoqIA+3CQYeubnRwIga25zHsADUgJjAQTqzZWxrJH1p4LPXTLqcjEUrW147B2866sX8/PTEcug5A0TQZHs1CnoygEa9cjEYlbx/ZRpNOwNG0je7IeNQ/u8psP7EZ7ZeFiQHEUSJ5URlEoMzcDJsvmZoOyv9nBTGiUlj3jThCFHcsU5uDjTlxfPNLtM7vDNDFf6nkWEFutsyZ0S/HyJUho=
    - secure: RRa1g7i8n+3fOUKQQRWd+EFMb7fMxQcS9qjIQqw5gEkkIsRjfsszKfGBLw6f1PLsy/NSFpgejHkrJko0UkWS1ei93TEsg1OyjNg4xKWfegiN/i+GhAAkt9yamOlw2bhZe9wfoN8vscLkZcrfFO7h8cphvELQof2STgYv3G/t48sUxxhYcLqqb8OAp1+SW+XUXd+ugB/QLfOwqi4ojkVDvw4M1VxYRbp+tURufUl32B/jeDC++PlmVtWDDiwte+ow1w5rC0jb4W3C0IpZ93MOCRnpEp/owrMeUmBTdBT+c6Ad6aOvOTy+2OUMvRsIAaUCvHNmgA4D6nty9zLjMFku78n1yskvW/UNvi0yjxnFpmK76J0/fmvyUtAIBw8XBJbB2C2EKTCM6QeIRdXI00U0iOPTtAn3ZLs3eog65Xrv8jDGUtpZjOs8GUPoikbfztZcnM8fM+RojEvrO1FX6VXvr2kKgcd4JF1LhIRfsxM/AFBoo1UNYCl2C36Ti9DuUt9+9vRgDdh9EqHTasMwS4wq/3tIVqByf/k5sivKJyAiJBmFnKzEzd06+rK9OJbhxuY7Vh6Tb85IblMxMCGCehwSAjMqsEqW0qqWoxVd9pTvP/1EZwWI26puxD1Ewuy5XGcSxvScdGPYlqSgqAYN1z1ZKV48Y8D1pSk4wMj6LFy1UC0=
    - secure: p25mJtGFm/2cXY5wSpDUmXvDmbJVN8QoDTJ0iVcb0N0MvvEoFD1kAR4rb8pKreT8wHgKZbnQO+H3kg0k8p8cmZwMlGtXvuhqz3bdWAkRcBVdbVkVE8qSuDgrWZbIJYK3yT20eWpjmFm6whnYKpE/oyoOww8bSrIk/GTf8koqCMyDIOM2QvMDh/uaTEH4WezhxVcIGbUPwx3jB42m9GwoUpWrtmgcnCr5MKeNUynMpnFhofBzX9Hkiq3AhWaMqAfTyGyX4mktgrF3hjQia7HaV2aAZ8qT5OMPuNIbUEWJNqlq6sa6pupZ1oRFWAGiCudMc7ai/iW+v0UDp3UIDzM95rqfxU/v1OYSxgepIJQwF6cnmQbjpR/MFkmF3va/o63XtYd+98e419NNY72Ne9FxaCrxAnax0wYvpVLnuD9weNx4N++Y6JOwW1TFDU6eZ13/JdgMc9CTuGSXD8qge2aMpi2m6kD3/LZNquiraaxd8x2GqqvaoyrE9A6bskTZIbknc2enZ+r8F2VVB82Y1M5677HGvsbiGUx3RLNTEc+N30fpV+LJGYXWy9+Kr5UN4pRy0/PWQCZCb3dLxg0rXYxCGcqz6o5Xjk/zJahLfd0ZX87EtmgqtAlv7H/8lAf7ZM9BJPaKoyWriFL0OE6oNFQsvEMNJaYGCrJQzmHG1wOib/U=
cache:
  timeout: 1200
  directories:
    - "$HOME/.npm"
before_install:
  - export TRAVIS_REPO_OWNER=${TRAVIS_REPO_SLUG%/*}
  - export TRAVIS_REPO_NAME=${TRAVIS_REPO_SLUG#*/}
  - uname -a
  - lscpu
  - npm install -g npm
  - npm install -g semantic-release
before_script:
  - npm run pretest
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run cover
after_script:
  - npm run coveralls
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
before_deploy:
  - git config --local user.name "$TRAVIS_AUTHOR_NAME"
  - git config --local user.email "$TRAVIS_AUTHOR_EMAIL"
deploy:
  provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    branch: master
    node: 8
notifications:
  slack:
    secure: hhOE/vJy8W5QOo1pQGKuhp0jYVjg2sNTzOlM9a/qveiYHsFVJ4bnAe0xdX8YRPPbQ9n5NMAG5Zlnp3GSUFfmzD4dZ4Sf+XrHjQSBeloDkhRhFnIuPaf5oFNh45kn2H4TrTpASOgUQsW/7auM6EHR+k5BvL+z1596kqWlmHgFVXKw18eQFTXIq8LthW7HdM5BGTF88oZ3pwyC4VYArGpLZK8yizgtolWxiXH0qZxY6ij3UPkmo8MwNl3SuCUtSfFBoYGMzDTM3SZF92dtNHvsSM2xzCx2q/0jPDBFszrLiwybC8dzUvWzYl2EKPtI26p15ASMClhzrXK4WY6zuY1gtHSNPX0ToV3Vgz8ys5mrHE6eWhpu2MH3YiVDLXd76WbYOO22Cr6SgFIaAQ+DKn88Nq48WKNH0d4S3h9KTF5h7bnYaWsJs6avNScj1KSDzy37VoHqawgjfy3CB8JzGZLQZKeI3f/b4Z1QswNfUr35p3Rvt5IwYKP5OZiX+uCSNNmyGc1fqbUSpb9ThZ7dYdprDiFeQT2vrIUWx58Eggd+sxwzjMid8YMyHCfuuGNoMC8VrlM9ejpDYblEkcMKLbePRMnhZV5pi2WS759MREdTUtp34jCCS5UwsxyKVVCbnT+7o2ji8Y1BmMwTUtZ8rFAf3feKkzVnWhBs+ubKAMWahbc=
