language: node_js
dist: trusty
node_js:
- '10'
- '8'
- '6'
matrix:
  fast_finish: true
  allow_failures:
    - node: 6
before_install:
- uname -a
- lscpu
- npm install -g npm
- export NODE_ENV=prd;
- git config --global url."https://github.com/".insteadOf ssh://git@github.com/
- git config --global url."https://".insteadOf ssh://
script: npm run travis
before_deploy:
- mkdir -p ../dpl_cd_upload
- tar -zcf ../dpl_cd_upload/me.pseudoimage.tar.gz -C ./ .
- git config --local user.name "Travis"
- export TRAVIS_AUTHOR=travis@randytarampi.ca
- export COMMIT_AUTHOR=`git --no-pager show -s --format='%ae' \`git rev-parse\``
- git config --local user.email $TRAVIS_AUTHOR
- if [[ -z "$TRAVIS_TAG" ]]; then
  npm version "0.0.0-`date -u +%s`";
  fi;
deploy:
  provider: releases
  api_key:
    secure: k7UmDAeRJccHAoha16KBIH7XVZ4ch5GXk7WO7dIEVGC+yo6PcTSfeflanWL+86LztEoJ3d/0HaqCR8jU3iUeRkd2iqsdSca5daHBH+ajomjax4E0PW1WNs3UfWWBTv6hfqH7BU6l0M+Hp0ekO0z7tqSBwcm0d8FZZ0ohcg1Zx6Ym0r8NgaXXUr7VwIqtdk5PgqM+k9NPGlH/6B+z/dYTuWLriDIVLxlAdD3OwcD3QbeXdTnT/e1APrzt3TJSPXhO4AHakonZ/7ZOD2qjgWlCRArW+To2xedviEANKX/TqC6xWWusu8PAnK22rEn6x8OCD+XrvP+eIjTwzX6/9WfalYPRq7Roc2Gt98xEyzKt6aeG1YKLQPgBqR3/JmYgALhsRRn1H2PQF8Cgm48ExGd4VJczYocAAVCN1+YvK0SwGvpLgqrVOdhn2AWbW7jzOx4Zat/jwmvO63JTv70blhMJ3kRTBfFBhE3guxaFJsCh5Gd8/G1s2gEBU46gduJNyuGYgVQSCQAAVJQ/8GHQOkO5KbcJxsDqJiTYmVo+EOLcsFAXr1dSRrj+SwGlyD2RjmZ6wZBnHlLMhRPZqphpCeVarHkpU78dHc6kym06CCYQvpVvcrLs2sCbzL7qD0jsebGC37D/EA9xTZg7XLJWlNlI8EGNFIE8CeiFKFDBs9wIBuo=
  file: me.pseudoimage.tar.gz
  skip_cleanup: true
  on:
    branch: master
    node: 8
after_deploy:
- git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} HEAD:master;
notifications:
  slack:
    secure: gi2d1wiL65m+Z+Dnp/5GGb5c9FsggYLWwlCiHwa/AZkl0XPaGVQnTxi/+EbL0VVh0v6MZ1gWQlSpYZ9QZknZfcicBiWoO5BxsNqGmwn9/0Rt42IS0imJB8Lld3Bnl/DDEP4+1N6i0J2R45QIDFrvXtuobn+ShFif7RSiXoAn+d8FKQmGoTzYte6wD7oYa31dufMnSGky/9hAkMshuwRTKKDv8WRfeK3X0Z4pBF2ZILPz3Esnnzum/MaK7XkE0DPyZ1zySBaM4VPpE+6S/rswQLbFYqN02XKH8ld4oVE6Zr+9LgRQamlq19r/7otbCuiSVHgVKAS3HID9pTC9rxaRQBp7lJRNrr0C9F7+q2zdUMV0aSB1utCf+HIqIlvmTeGVNMU2z0YcuXw+bR0yJviE7sO86k+EkSt/PH89ewGDSfZZ8+tJEl9kcxtXvwS8OAz9twOhtAStzF2IsORZQPQPxE4KRbg8NfXZuK4lEEXxytS17a1RmWjsH3MmoKEXEU2ZxrGyj1gUk3rpUQljL8QT3mkmCaGMJ/k3akK5bMJsDVfWE+YF8a0FJVQHrSW6TWw8zzEgmTDlpKwfXiO3QbgtdawoThzA417/kASmJrxyZTLCvWg/YsTlifxCJR0b+OZK3r7BDHIDM1HeOdpjptel/73xTPeMmKyp2wpH3knMSNA=
